# Generated by Django 5.2.8 on 2025-11-25 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(db_index=True, max_length=255)),
                ('tipo_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('nit', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gasto', models.CharField(max_length=255)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(blank=True, choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('ANULADO', 'Anulado')], max_length=50, null=True)),
                ('comprobante', models.TextField(blank=True, null=True)),
                ('id_caso', models.ForeignKey(blank=True, db_column='id_caso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='casos.caso')),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='finanzas.proveedor')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'gastos',
            },
        ),
    ]
