# Generated by Django 5.2.8 on 2025-11-25 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id_donante', models.AutoField(primary_key=True, serialize=False)),
                ('donante', models.CharField(db_index=True, max_length=255)),
                ('tipo_id', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], max_length=50, null=True)),
                ('identificacion', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('correo', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_donante', models.CharField(blank=True, choices=[('PERSONA_NATURAL', 'Persona Natural'), ('EMPRESA', 'Empresa'), ('FUNDACION', 'Fundación'), ('OTRO', 'Otro')], max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('canal_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('consentimiento', models.BooleanField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('archivos', models.JSONField(blank=True, help_text='Metadatos de archivos adjuntos', null=True)),
            ],
            options={
                'verbose_name': 'Donante',
                'verbose_name_plural': 'Donantes',
                'db_table': 'donantes',
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_donacion', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('WOMPI', 'Wompi'), ('PAYU', 'PayU'), ('OTRO', 'Otro')], max_length=100, null=True)),
                ('estado', models.CharField(blank=True, choices=[('APROBADA', 'Aprobada'), ('PENDIENTE', 'Pendiente'), ('RECHAZADA', 'Rechazada')], max_length=50, null=True)),
                ('comprobante', models.TextField(blank=True, null=True)),
                ('id_caso', models.ForeignKey(blank=True, db_column='id_caso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='casos.caso')),
                ('id_donante', models.ForeignKey(blank=True, db_column='id_donante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='donaciones.donante')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donaciones',
            },
        ),
    ]
