# Generated by Django 5.2.8 on 2025-11-25 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HogarDePaso',
            fields=[
                ('id_hogar_de_paso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hogar', models.CharField(db_index=True, max_length=255)),
                ('tipo_hogar', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('cupo_maximo', models.IntegerField(blank=True, null=True)),
                ('tarifa_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desempeno', models.TextField(blank=True, null=True)),
                ('ultimo_contacto', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hogar de Paso',
                'verbose_name_plural': 'Hogares de Paso',
                'db_table': 'hogar_de_paso',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_caso', models.CharField(db_index=True, max_length=255)),
                ('estado', models.CharField(blank=True, choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('EN_TRATAMIENTO', 'En Tratamiento'), ('ADOPTADO', 'Adoptado'), ('FALLECIDO', 'Fallecido')], max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('veterinaria', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('archivo', models.JSONField(blank=True, help_text='Historia clínica o archivos adjuntos', null=True)),
                ('id_hogar_de_paso', models.ForeignKey(blank=True, db_column='id_hogar_de_paso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='casos.hogardepaso')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'db_table': 'casos',
            },
        ),
    ]
